// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	repo "github.com/openshift-assisted/assisted-events-streams/internal/migrations/domain/repo"
)

// MockCacheReader is a mock of CacheReader interface.
type MockCacheReader struct {
	ctrl     *gomock.Controller
	recorder *MockCacheReaderMockRecorder
}

// MockCacheReaderMockRecorder is the mock recorder for MockCacheReader.
type MockCacheReaderMockRecorder struct {
	mock *MockCacheReader
}

// NewMockCacheReader creates a new mock instance.
func NewMockCacheReader(ctrl *gomock.Controller) *MockCacheReader {
	mock := &MockCacheReader{ctrl: ctrl}
	mock.recorder = &MockCacheReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheReader) EXPECT() *MockCacheReaderMockRecorder {
	return m.recorder
}

// ListHValues mocks base method.
func (m *MockCacheReader) ListHValues(ctx context.Context, output chan<- repo.KeyValue, opts repo.ListHValuesOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHValues", ctx, output, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListHValues indicates an expected call of ListHValues.
func (mr *MockCacheReaderMockRecorder) ListHValues(ctx, output, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHValues", reflect.TypeOf((*MockCacheReader)(nil).ListHValues), ctx, output, opts)
}

// ListKeys mocks base method.
func (m *MockCacheReader) ListKeys(ctx context.Context, output chan<- string, opts repo.ListKeysOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKeys", ctx, output, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListKeys indicates an expected call of ListKeys.
func (mr *MockCacheReaderMockRecorder) ListKeys(ctx, output, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKeys", reflect.TypeOf((*MockCacheReader)(nil).ListKeys), ctx, output, opts)
}

// MockCacheWriter is a mock of CacheWriter interface.
type MockCacheWriter struct {
	ctrl     *gomock.Controller
	recorder *MockCacheWriterMockRecorder
}

// MockCacheWriterMockRecorder is the mock recorder for MockCacheWriter.
type MockCacheWriterMockRecorder struct {
	mock *MockCacheWriter
}

// NewMockCacheWriter creates a new mock instance.
func NewMockCacheWriter(ctrl *gomock.Controller) *MockCacheWriter {
	mock := &MockCacheWriter{ctrl: ctrl}
	mock.recorder = &MockCacheWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheWriter) EXPECT() *MockCacheWriterMockRecorder {
	return m.recorder
}

// AddClusters mocks base method.
func (m *MockCacheWriter) AddClusters(ctx context.Context, kvs []repo.KeyValue, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddClusters", ctx, kvs, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddClusters indicates an expected call of AddClusters.
func (mr *MockCacheWriterMockRecorder) AddClusters(ctx, kvs, expiration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddClusters", reflect.TypeOf((*MockCacheWriter)(nil).AddClusters), ctx, kvs, expiration)
}

// DeleteKeys mocks base method.
func (m *MockCacheWriter) DeleteKeys(ctx context.Context, keys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKeys", ctx, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKeys indicates an expected call of DeleteKeys.
func (mr *MockCacheWriterMockRecorder) DeleteKeys(ctx, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKeys", reflect.TypeOf((*MockCacheWriter)(nil).DeleteKeys), ctx, keys)
}

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// AddClusters mocks base method.
func (m *MockCache) AddClusters(ctx context.Context, kvs []repo.KeyValue, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddClusters", ctx, kvs, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddClusters indicates an expected call of AddClusters.
func (mr *MockCacheMockRecorder) AddClusters(ctx, kvs, expiration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddClusters", reflect.TypeOf((*MockCache)(nil).AddClusters), ctx, kvs, expiration)
}

// DeleteKeys mocks base method.
func (m *MockCache) DeleteKeys(ctx context.Context, keys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKeys", ctx, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKeys indicates an expected call of DeleteKeys.
func (mr *MockCacheMockRecorder) DeleteKeys(ctx, keys interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKeys", reflect.TypeOf((*MockCache)(nil).DeleteKeys), ctx, keys)
}

// ListHValues mocks base method.
func (m *MockCache) ListHValues(ctx context.Context, output chan<- repo.KeyValue, opts repo.ListHValuesOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHValues", ctx, output, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListHValues indicates an expected call of ListHValues.
func (mr *MockCacheMockRecorder) ListHValues(ctx, output, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHValues", reflect.TypeOf((*MockCache)(nil).ListHValues), ctx, output, opts)
}

// ListKeys mocks base method.
func (m *MockCache) ListKeys(ctx context.Context, output chan<- string, opts repo.ListKeysOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKeys", ctx, output, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListKeys indicates an expected call of ListKeys.
func (mr *MockCacheMockRecorder) ListKeys(ctx, output, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKeys", reflect.TypeOf((*MockCache)(nil).ListKeys), ctx, output, opts)
}
